// Do not allow concurrent builds
properties([disableConcurrentBuilds()])

pipeline {
    agent any

    options {
        // Max # of builds to keep
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }

    stages {
        stage("Terraform AWS EKS") {
            steps {
                build job: 'Terraform AWS EKS'
                sh 'sleep 10'
            }
        }
        stage("Deploy Drupal (helm)") {
            steps {
                build job: 'Deploy Drupal (helm)'
            }
        }
        stage("Landing Page Build and Deploy") {
            steps {
                build job: 'Landing Page Build and Deploy'
            }
        }
        stage("Deploy Prometheus Grafana") {
            steps {
                build job: 'Deploy Prometheus Grafana (helm)'
            }
        }
    }
}