properties([disableConcurrentBuilds()])
properties([pipelineTriggers([githubPush()])])

pipeline {
    agent any

    options {
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }

    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION='eu-central-1'
    }
 
    stages {
        stage("Deploy Prometheus Grafana") {
            steps {
                sh '''#!/bin/bash
                    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
                    helm install prometheus prometheus-community/kube-prometheus-stack
                    echo "Run-on your computer"
                    echo "  kubectl port-forward deploy/prometheus-grafana 3000"
                '''
            }
        }
    }
}
 
