// Do not allow concurrent builds
properties([disableConcurrentBuilds()])
// GitHub hook trigger for GITScm polling
properties([pipelineTriggers([githubPush()])])

pipeline {
    agent any

    options {
        // Max # of builds to keep
        buildDiscarder(logRotator(numToKeepStr: '3'))
    }

    environment { 
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION='eu-central-1'
    }
 
    stages {
        stage("Helm Deploy Drupal") {
            steps {
                sh '''#!/bin/bash
                    cd Oleksandr_Varchenko/helm-drupal/ && \
                    helm install test-drupal .
                    export SERVICE_IP=$(kubectl get svc --namespace default test-drupal --template "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
                    echo "Drupal URL: http://$SERVICE_IP/"
                    echo Username: user
                    echo Password: $(kubectl get secret --namespace default test-drupal -o jsonpath="{.data.drupal-password}" | base64 --decode)
                '''
            }
        }
    }
}
 
