properties([disableConcurrentBuilds()])

pipeline {
    agent any

    environment { 
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION='eu-central-1'
    }
 
    stages {
        stage("Terraform AWS EKS") {
            steps {
                sh '''#!/bin/bash
                    cd Oleksandr_Varchenko/terraform-k8s/
                    terraform init
                    terraform $TERRAFORM_APPLY_DESTROY -auto-approve
                    if [ $TERRAFORM_APPLY_DESTROY == "apply" ] then 
                        terraform output kubeconfig | sed -e "/EOT/d" -e "/^$/d" > ~/.kube/config
                    fi 
                '''
            }
        }
    }
}
